### ISSUE TITLE
Map Question

### ISSUE THREAD

**Issue by Lugulbanda** [Safecast/Tilemap#10]
Hi, i have a question to this section of the Japan map
http://safecast.org/tilemap/?y=34.8563&x=137.6555&z=14&l=0&m=5
i see there is a high dosis in a few streets and next to them there is nearly nothing

i can understand if this region has seen some rainshower, but the blue street wich is piercing trugh the red to yellow glow is somehow unnatural, special on the crossing.

is this regarding to the time the measurement was made? cant beleve something that high can go to dark blue !!

would be a strange coincidence that only the temples got its dose and the infrastruckture around not...
is that brought by rain, or is there uranium in the Mountains around ?

**Comment by seanbonner** [comment]
The streets being more heavily trafficked clean up quicker. The same can be seen in Chernobyl. Additionally the streets are measured more frequently than the off-path locations so that’s reflected in the data as well.
-sean


Sean Bonner
Co-Founder, Director of Global Operations
Safecast.org | pgp key

On February 9, 2018 at 1:22:05 AM, Lugulbanda (notifications@github.com) wrote:

Hi, i have a question to this section of the Japan map
http://safecast.org/tilemap/?y=34.8563&x=137.6555&z=14&l=0&m=5
i see there is a high dosis in a few streets and next to them there is nearly nothing

i can understand if this region has seen some rainshower, but the blue street wich is piercing trugh the red to yellow glow is somehow unnatural, special on the crossing.

is this regarding to the time the measurement was made? cant beleve something that high can go to dark blue !!

would be a strange coincidence that only the temples got its dose and the infrastruckture around not...
is that brought by rain, or is there uranium in the Mountains around ?

**Comment by Azby** [comment]
I took a closer look. This area is in Shizuoka, south of Tokyo. Any elevated radiation levels are not likely to be from Fukushima. It’s plausible that it is natural background. The data was collected by GLC, who are very experienced, about a year ago. It is the only data we have for this particular area. It would be nice to have more data from the same area. 
For comparison, it is similar to this area in France, which is confirmed natural background:
http://safecast.org/tilemap/?y=46.052&x=1.431&z=12&l=1&m=2 <http://safecast.org/tilemap/?y=46.052&x=1.431&z=12&l=1&m=2>

Azby

**Comment by Lugulbanda** [comment]
there are some higher readings in the coastlines of italy and Malaysia, wich look strange, in italy it may be mafia related nuklear waste dumps, i read in the press, but for this the costline near neaple is a bit to large, maybe contamination of the sensor? 

Gesendet mit der GMX Mail App

Am 09.02.18 um 04:29 schrieb Azby

> I took a closer look. This area is in Shizuoka, south of Tokyo. Any elevated radiation levels are not likely to be from Fukushima. It’s plausible that it is natural background. The data was collected by GLC, who are very experienced, about a year ago. It is the only data we have for this particular area. It would be nice to have more data from the same area. 
> For comparison, it is similar to this area in France, which is confirmed natural background:
> http://safecast.org/tilemap/?y=46.052&x=1.431&z=12&l=1&m=2 <http://safecast.org/tilemap/?y=46.052&x=1.431&z=12&l=1&m=2>
> 
> Azby
> 
>

**Comment by Azby** [comment]
I looked again at those locations just now, and saw some elevated levels in both Napoli and the west coast of Malaysia north of Kuala Lumpur. I didn't see anything in particular actually on the coast near Napoli though. The coastal area of Malaysia has levels in the 0.2uSv/hr range. The center of Napoli is in the 0.3-0.4 uSv/hr range. Both can be considered somewhat elevated, but most likely due to natural radiation. I don't think any kind of waste-related explanation is warranted. In fact both are within the range of "normal" natural background radiation.

What we see in Napoli is actually typical of many old European towns, very likely due to the old building material. Take a look at Santiago di Compostela for instance. Or Rome (although we have flagged a couple of anomalies there). Also, take a look at Hong Kong, which has been very thoroughly surveyed by our large group of volunteers there. The elevated radiation there is confirmed to be from granite.

One of the aspects of the Safecast project that has the greatest impact is that we are able to learn what levels of radiation are typical in locations all over the world. Tis will make it easier for us to detect unusual increases. But people are sometimes surprised to learn that humans have been living for centuries in many places in the world that have higher than average radiation levels.

Cheers,
Azby

**Comment by julovi** [comment]
Hi Azby,

> 
>  Or Rome (although we have flagged a couple of anomalies there). 

I somehow missed the discussion about the anomalies in Rome, do you mind to elaborate what kind of anomalies you found there?

I’m very interested…

Cheers,

Julian.

**Comment by Azby** [comment]
Most of Rome has elevated natural background levels. But our system captured a few spots which are likely to be from sending the bGeigie through an x-ray machine. We flagged those with an "anomaly" icon (? in a box) and a short description.  If the anomaly icons are not showing, you can turn them on from the pop-out controls on the left-hand side.  About midway down is "Interest," and the "Anomalies" toggle switch is below that.

Azby

**Comment by Lugulbanda** [comment]
as i measured around in my area i see we have lvls between 0.1 and 0,4 also i get sometimes measurements wich are 0.4 in places were i had lesser bevore or sometimes after, i think it has to do with the weather condition, so i understand what sean sayed with mixed measurements and 10% accepteble error, so if we call radiation up to 0.4 as normal? why is then a colorshange between 0.3 and 0.4 i understand that u have to do it on a certain point, but wouldnt it be better to adjust the colorchange by 0.1? 0–0.2 dark normal 0.3-0.4 elevated dark blue and 0.5- as mor then elevated? i know u guys took alot thoughts in this, iam not so much a number specialist, but i love to work with visualisatons and in a see of dark blue an elevated lightcblue shines like the sun.

Gesendet mit der GMX Mail App

Am 13.02.18 um 12:16 schrieb Azby

**Comment by Lugulbanda** [comment]
the thing wich surpriced me most was, that i indoor hat 3-5 times higher radiation then outside, until u vent out the radon gas...
a lesson i got from savecast is venting a room is not only getting fresh air, its also get rid of the Radon Gas...
 

Gesendet: Dienstag, 13. Februar 2018 um 12:16 Uhr
Von: Azby <notifications@github.com>

One of the aspects of the Safecast project that has the greatest impact is that we are able to learn what levels of radiation are typical in locations all over the world. Tis will make it easier for us to detect unusual increases. But people are sometimes surprised to learn that humans have been living for centuries in many places in the world that have higher than average radiation levels.

Cheers,
Azby
